# Generated by Django 4.2 on 2023-04-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='coments',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
