# Generated by Django 4.2 on 2023-04-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_coments_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='coments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
