# Generated by Django 4.2 on 2023-04-24 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_coments_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='coments',
        ),
    ]
