# Generated by Django 4.2 on 2023-04-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='coment',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
